//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buru.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Bug
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bug()
        {
            this.ListBugs = new HashSet<ListBug>();
        }
    
        public int BugId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Steps { get; set; }
        public string Attachment { get; set; }
        public string Assignee { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> CreatedDate { get; set; }
        [DataType(DataType.Date)]
       
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public string Severity { get; set; }
        public string Kind { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListBug> ListBugs { get; set; }
    }
}
