//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buru.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BuruDataEntities2 : DbContext
    {
        public BuruDataEntities2()
            : base("name=BuruDataEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Akun> Akuns { get; set; }
        public virtual DbSet<Bug> Bugs { get; set; }
        public virtual DbSet<ListBug> ListBugs { get; set; }
        public virtual DbSet<ListUser> ListUsers { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
    }
}
